# Generated by Django 3.0.7 on 2020-06-16 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_auto_20200616_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 16, 19, 23, 21, 40662)),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
