# Generated by Django 3.0.7 on 2020-06-17 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_auto_20200617_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keywords',
            old_name='default_keyword',
            new_name='default_search_keyword',
        ),
        migrations.AlterField(
            model_name='analysis',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 16, 9, 22, 303420)),
        ),
    ]
