# Generated by Django 3.0.7 on 2020-06-17 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0010_auto_20200617_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 17, 40, 16, 266604)),
        ),
    ]
