# Generated by Django 3.0.7 on 2020-06-17 18:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0012_auto_20200617_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 23, 38, 12, 473954)),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='for_analysis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='analysis.Analysis'),
        ),
    ]
