# Generated by Django 3.0.7 on 2020-06-17 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0013_auto_20200617_2338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='for_analysis',
            new_name='analysis',
        ),
        migrations.AlterField(
            model_name='analysis',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 18, 0, 4, 25, 600204)),
        ),
    ]
