# Generated by Django 3.0.7 on 2020-06-21 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0018_auto_20200618_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberOfTweetsToFetch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_tweets', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='analysis',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 21, 9, 50, 39, 295607)),
        ),
    ]
