# Generated by Django 3.0.7 on 2020-06-21 04:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0019_auto_20200621_0950'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NumberOfTweetsToFetch',
            new_name='Constants',
        ),
        migrations.AlterField(
            model_name='analysis',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 21, 9, 51, 55, 377006)),
        ),
    ]
