# Generated by Django 3.0.7 on 2020-06-21 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0021_auto_20200621_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 21, 18, 32, 27, 248381)),
        ),
    ]
