# Generated by Django 3.0.7 on 2020-06-21 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0022_auto_20200621_1832'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Constants',
            new_name='Constant',
        ),
        migrations.AlterField(
            model_name='analysis',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 21, 18, 40, 50, 567240)),
        ),
    ]
