# Generated by Django 3.0.7 on 2020-06-21 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0023_auto_20200621_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constant',
            name='number_of_tweets_to_fetch_for_analysis',
        ),
        migrations.AddField(
            model_name='constant',
            name='name_with_underscore',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='constant',
            name='value',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analysis',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 21, 18, 43, 34, 937600)),
        ),
    ]
