# Generated by Django 3.0.7 on 2020-06-23 14:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0027_auto_20200621_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 23, 20, 7, 36, 190190)),
        ),
    ]
