# Generated by Django 3.0.7 on 2020-06-25 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0028_auto_20200623_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='trending_hashtags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 26, 1, 5, 37, 412543)),
        ),
    ]
