# Generated by Django 3.0.8 on 2020-07-02 09:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0029_auto_20200626_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='statewise_tweets',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 2, 14, 32, 49, 575092)),
        ),
    ]
