# Generated by Django 3.0.8 on 2020-07-02 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0030_auto_20200702_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 2, 15, 24, 16, 962493)),
        ),
    ]
