# Generated by Django 3.0.8 on 2020-07-04 07:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0031_auto_20200702_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 4, 13, 10, 21, 62257)),
        ),
    ]
