# Generated by Django 3.0.8 on 2020-07-04 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0033_auto_20200704_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 4, 20, 58, 57, 601312)),
        ),
    ]
