# Generated by Django 3.0.8 on 2020-07-04 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0034_auto_20200704_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 4, 21, 0, 22, 175015)),
        ),
    ]
