# Generated by Django 3.0.8 on 2020-07-04 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0035_auto_20200704_2100'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Constant',
        ),
        migrations.RenameField(
            model_name='analysis',
            old_name='trending_hashtags',
            new_name='datewise_tweets',
        ),
        migrations.RemoveField(
            model_name='analysis',
            name='tweets',
        ),
        migrations.AlterField(
            model_name='analysis',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 4, 23, 45, 22, 192796)),
        ),
    ]
