# Generated by Django 3.0.8 on 2020-07-04 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0036_auto_20200704_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 4, 23, 46, 1, 174105)),
        ),
    ]
