# Generated by Django 3.0.8 on 2020-07-05 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0037_auto_20200704_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 11, 9, 45, 720491)),
        ),
    ]
