# Generated by Django 3.0.8 on 2020-07-05 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0038_auto_20200705_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 14, 30, 27, 190421)),
        ),
    ]
