# Generated by Django 3.0.8 on 2020-07-06 08:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0040_auto_20200706_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 6, 14, 4, 10, 646024)),
        ),
    ]
