# Generated by Django 3.0.8 on 2020-07-08 05:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0046_auto_20200706_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 8, 11, 16, 12, 234797)),
        ),
    ]
