# Generated by Django 3.0.8 on 2020-07-08 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0048_auto_20200708_1306'),
        ('analysis', '0048_auto_20200708_1229'),
    ]

    operations = [
    ]
