# Generated by Django 3.0.8 on 2020-07-08 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0049_merge_20200708_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 8, 14, 24, 4, 705694)),
        ),
    ]
