# Generated by Django 3.0.8 on 2020-07-09 05:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0050_auto_20200708_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 9, 11, 29, 21, 704413)),
        ),
    ]
