# Generated by Django 3.0.8 on 2020-07-09 14:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0053_auto_20200709_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 9, 19, 48, 25, 21776)),
        ),
    ]
