# Generated by Django 3.0.8 on 2020-07-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0003_nooftrendingkeywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumOfTweetsPerStatePerDefaultKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='NumOfTweets',
            new_name='NumOfTweetsPerDay',
        ),
    ]
