# Generated by Django 3.0.8 on 2020-07-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0004_auto_20200708_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumOfTweetsPerState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
    ]
