# Generated by Django 3.0.8 on 2020-07-09 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0005_numoftweetsperstate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NumOfTweetsPerStatePerDefaultKeyword',
        ),
    ]
