# Generated by Django 3.0.8 on 2020-07-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constants', '0006_delete_numoftweetsperstateperdefaultkeyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daysoftrendingtweets',
            name='value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='noofpopulartweets',
            name='value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nooftrendingkeywords',
            name='value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='numoftweetsperday',
            name='value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='numoftweetsperstate',
            name='value',
            field=models.IntegerField(),
        ),
    ]
